scan_filter_chain:
  - name: range
    type: laser_filters/LaserScanRangeFilter
    params:
      use_message_range_limits: false
      lower_threshold: 0.2
      upper_threshold: .inf
      lower_replacement_value: -.inf
      upper_replacement_value: .inf
# - name: shadows
#   type: laser_filters/ScanShadowsFilter
#   params:
#     min_angle: 10
#     max_angle: 170
#     neighbors: 20
#     window: 1
  - name: footprint_filter
    type: laser_filters/LaserScanFootprintFilter
    params:
      inscribed_radius: 0.2
  - name: angle_0
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
      lower_angle: 1.02
      upper_angle: 1.26
  - name: angle_1
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
      lower_angle: 1.90
      upper_angle: 2.14
  - name: angle_2
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
      lower_angle: -2.11
      upper_angle: -1.89
  - name: angle_3
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
      lower_angle: -1.27
      upper_angle: -1.01