
# Most params are loaded from the running configuration file (config.yaml).

method_list: ["orb3", "gfgg", "hector_slam"] # Methods list to be evaluated.
save_to_result_dir: True # Whether to save data to the existing result directory (defined in the running config file)
output_dir: "/tmp" # Define the output dir.
save_data: True # Whether to save data.
overwrite_data: True # Whether to overwrite existing evaluation data.
evaluation_prefix: "lidar" # Prefix of evaluation.
log_to_file: True # Whether logging to file.
load_evaluation: True # Whether to load existing evaluation data.
save_figs: True

