# hdl_slam
slam_method: "fast_lio2"
mode: "slam"
enable_msf: false
slam_sensor_type: "laser"
source_msg_parent_frame: "base_footprint"
source_msg_child_frame: "base_footprint"
loops: 1
need_map_to_odom_tf: true