# orb3
slam_method: "orb3"
mode: "slam"
feature_num: 800
enable_msf: false
slam_sensor_type: "stereo"
source_msg_parent_frame: "camera_infra1_frame"
# source_msg_parent_frame: "left_camera_frame"
source_msg_child_frame: "camera_infra1_optical_frame" # "gyro_link" # msf
# source_msg_child_frame: "left_camera_optical_frame" # "gyro_link" # msf
loops: 1
need_map_to_odom_tf: true
