image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [792.96339,   0.     , 643.8151 ,
           0.     , 793.36333, 363.58227,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.112172, -0.155631, 0.003064, -0.000947, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [798.60681,   0.     , 642.16486,   0.     ,
           0.     , 808.76593, 364.90064,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]