image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [840.10575,   0.     , 653.83006,
           0.     , 842.7504 , 387.12646,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.109935, -0.173344, -0.002063, -0.002850, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [844.66486,   0.     , 650.30165,   0.     ,
           0.     , 858.31519, 385.44992,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
