image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [788.37055,   0.     , 607.10563,
           0.     , 791.59666, 369.4787 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.094941, -0.153766, 0.004054, -0.001484, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [781.40381,   0.     , 598.00832,   0.     ,
           0.     , 802.55518, 371.33327,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]